#!/bin/busybox sh

/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
echo "Mounted essential filesystems"

# Symlink busybox
/bin/busybox --install -s

hostname "initramfs"

echo

exec sh

