#!/bin/busybox ash

# mount the core filesystems
mount -t proc /proc /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# create the directories needed for installation of the applets
mkdir -p /usr /usr/bin /usr/sbin

# install symlinks for all the applets
/bin/busybox --install

clear

###

# Grab the hostname from /etc/hostname if it exists
[ -f /etc/hostname ] && HOSTNAME="$(cat /etc/hostname)"
# and default to "localhost"
[ -z "$HOSTNAME" ] && HOSTNAME=localhost

hostname "$HOSTNAME"

export HOSTNAME=$HOSTNAME

###

export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

###

#echo "trying to bring up eth0 "
#
#ifconfig eth0 up
#
#echo "trying to obtain a dhcp lease"
#
# TODO: move the script
# udhcpc -t 5 -q -s /script.sh

###

echo -e "\e[97m"
cat /etc/motd
echo ""
echo "Dropping you in a shell - have fun"
echo -e "\e[0m"

# Start a (job-controlling) shell
exec setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
